### PR TITLE
Let Users Change Votes Until Cards Are Shown

### PR DESCRIPTION
**Pull request by mattgill**
With this users can change votes until cards are shown (either when all players vote or when Show Votes is clicked).

I'm confident in the Vue change. No promises I didn't screw up the package files?

(I made my changes, 'npm run dev', validated functionality and committed)

### CODE REVIEW

**Comment by jwhulette** [comment]
Needs tests

**Comment by mattgill** [comment]
Done.

Changed the test setup slightly as a result since I don't have your computer.

Compose pulls in a headless chrome. If you have USE_CONTAINER_BROWSER=true in your .env I tweak DuskTestCase.php to use that.

One thing I did do was wire the app around a URL of 'planningpoker.test' just for my own sanity because depending on where you are localhost is many different things. _localhost_ still works locally. I also changed the port to 80 because if the APPURL needs to be at 8000 then we also need nginx to listen on 8000 if we are hopping between containers.

As for why I never saw players? Iit was actually pretty straightforward in the end.

So Dusk is calling out to the chrome container (if the env file is set). In the compose I tell chrome to find the app at Nginx.

Well when Chrome goes to broadcast it was going to :6001 at the _APPURL_. We never saw the log in nginx because well nginx was 80. Player login worked live because both of us were sending our computers at the server running the containers where 80 _and_ 6001 were exposed :-)

So I tweaked nginx to forward 6001 to supervisor. If you wanted to take it further you could probably not have to expose supervisor (or app?) on the host, but I didn't care enough to go further :-)

**Comment by mattgill** [comment]
Okay so I tried to fix the CI I broke but this last thing scares me with talk of Production going to make the storage directory.

So I get it. When I changed the app url in the Dusk env CI doesn't have a clue about planningpoker.test. So I swapped it for localhost and then saw the error regarding mkdir. I mean I realize I didn't put the :8000 back but that's shouldn't impact mkdir?

In the end please change whatever you need!

**Comment by mattgill** [comment]
I made one other change just now once I realized I should have made a new voting test (baseline vs expanded functionality).

One thing I can't explain though? When I first split it I mostly failed.

```
$ dce app php artisan dusk
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.

...E                                                                4 / 4 (100%)

Time: 00:08.883, Memory: 30.00 MB

There was 1 error:

1) Tests\Browser\VoteTest::test_users_can_change_vote_before_reveal
Facebook\WebDriver\Exception\InvalidSessionIdException: invalid session id

/var/www/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:107
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:371
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:612
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php:27
/var/www/html/vendor/php-webdriver/webdriver/lib/WebDriverOptions.php:166
/var/www/html/vendor/laravel/dusk/src/Browser.php:408
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:163
/var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:234
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:164
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:80
/var/www/html/tests/Browser/VoteTest.php:102

Caused by
Facebook\WebDriver\Exception\InvalidSessionIdException: invalid session id

/var/www/html/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:107
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:371
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:612
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php:27
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteTargetLocator.php:38
/var/www/html/vendor/laravel/dusk/src/Browser.php:295
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:143
/var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:234
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:149
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:70
/var/www/html/tests/Browser/VoteTest.php:102

ERRORS!
Tests: 4, Assertions: 9, Errors: 1.
ERROR: 2
```

But then it seems to be happy? I don't know if setUp can't spin up a new room fast enough? Debating throwing a sleep in setUp but I can't reproduce the failure anymore.

```
$ dce app php artisan dusk
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 00:11.386, Memory: 30.00 MB

OK (4 tests, 10 assertions)
thermal@Hurricane:~/SimplePointer$ dce app php artisan dusk
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 00:11.171, Memory: 30.00 MB

OK (4 tests, 10 assertions)

```


(And an aside to anyone reading this that may be curious about the casual nature of this PR thread...we know each other IRL)

**Comment by mattgill** [comment]
There! Build works again. So I don't know how you want to square developing not on your Mac and the GitHub Workflow, but I had to basically undo the .env.dusk.local changes I made to get Dusk to run in the container when it came to staging .env.dusk.local > .env in the Workflow.

Does it makes sense to have two .env.dusk.local files and if you need the alternate you pass that into Dusk? I'll let you decide which one would be the "alternate" in that flow.

**Review by jwhulette — APPROVED** [review]

**Pull request merged**
